from app import create_app, db
from models import User, Customer, Order, Measurement, Category
from faker import Faker
import random
from datetime import datetime, timedelta

app = create_app()
fake = Faker('en_IN')

def generate():
    with app.app_context():
        print("Starting data generation...")
        
        # 1. Create Categories
        cats_data = [
            ('Kurta', 'Male'), ('Sherwani', 'Male'), ('Safari Suit', 'Male'), 
            ('Formal Shirt', 'Male'), ('Formal Pant', 'Male'), 
            ('Blouse', 'Female'), ('Lehenga', 'Female'), ('Salwar Kameez', 'Female')
        ]
        db_cats = []
        for c_name, gender in cats_data:
            c = Category.query.filter_by(name=c_name).first()
            if not c:
                # Default fields for demo
                fields = [{"label": "Length", "type": "number"}, {"label": "Chest", "type": "number"}, {"label": "Waist", "type": "number"}]
                c = Category(name=c_name, gender=gender, is_custom=False, fields_json=fields)
                db.session.add(c)
            db_cats.append(c)
        db.session.commit()
        
        # Reload categories to get IDs
        db_cats = Category.query.all()
        print(f"Categories ready: {len(db_cats)}")

        # 2. Customers & Orders
        for i in range(10000):
            # Customer
            name = fake.name()
            # Ensure unique mobile roughly
            mobile = f"{random.randint(6000000000, 9999999999)}"
            city = fake.city()
            gender = random.choice(['Male', 'Female'])
            
            # Check if mobile exists to avoid error
            if Customer.query.filter_by(mobile=mobile).first():
                continue

            cust = Customer(
                name=name, 
                mobile=mobile, 
                city=city, 
                gender=gender,
                area=fake.street_name(),
                address=fake.address(),
                created_date=fake.date_time_between(start_date='-1y', end_date='now')
            )
            db.session.add(cust)
            db.session.flush() # Get cust.id

            # Measurement (One per category roughly or just random)
            # Create a measurement for a random category
            cat = random.choice(db_cats)
            meas_data = {"Length": str(random.randint(30, 45)), "Chest": str(random.randint(30, 50)), "Waist": str(random.randint(28, 48))}
            
            meas = Measurement(
                customer_id=cust.id,
                category_id=cat.id,
                measurements_json=meas_data,
                remarks="Generated by seed",
                date=datetime.now()
            )
            db.session.add(meas)

            # Order
            days_ago = random.randint(0, 365)
            o_date = datetime.now() - timedelta(days=days_ago)
            d_date = o_date + timedelta(days=random.randint(3, 15))
            
            # Items JSON
            rate = random.randint(500, 5000)
            items = [{"category": cat.name, "qty": 1, "price": rate, "total": rate}]
            
            total_amt = rate
            advance = random.choice([0, 500, rate//2, rate])
            balance = total_amt - advance
            
            if balance == 0:
                p_status = 'Paid'
            elif advance == 0:
                p_status = 'Pending'
            else:
                p_status = 'Partial'

            w_status = random.choice(['Working', 'Ready', 'Delivered'])

            order = Order(
                customer_id=cust.id,
                items=items,
                start_date=o_date,
                delivery_date=d_date,
                work_status=w_status,
                payment_status=p_status,
                total_amt=total_amt,
                advance=advance,
                balance=balance,
                payment_mode=random.choice(['Cash', 'UPI']),
                created_at=o_date
            )
            db.session.add(order)

            if i % 50 == 0:
                db.session.commit()
                print(f"Generated {i} entries...")

        db.session.commit()
        print("Successfully generated 1000 entries.")

if __name__ == "__main__":
    generate()
